export const BREEDS_LIST: string[] = [
  'Affenpinscher', 'Afghan Hound', 'Airedale Terrier', 'Akita', 'Alaskan Malamute',
  'American Bulldog', 'American Eskimo Dog', 'American Foxhound', 'American Pit Bull Terrier',
  'American Staffordshire Terrier', 'Australian Cattle Dog', 'Australian Shepherd',
  'Australian Terrier', 'Basenji', 'Basset Hound', 'Beagle', 'Bearded Collie',
  'Belgian Malinois', 'Belgian Sheepdog', 'Belgian Tervuren', 'Bernese Mountain Dog',
  'Bichon Frise', 'Bloodhound', 'Border Collie', 'Border Terrier', 'Boston Terrier',
  'Boxer', 'Brittany', 'Brussels Griffon', 'Bull Terrier', 'Bulldog', 'Bullmastiff',
  'Cairn Terrier', 'Cavalier King Charles Spaniel', 'Chesapeake Bay Retriever', 'Chihuahua',
  'Chinese Crested', 'Chinese Shar-Pei', 'Chow Chow', 'Clumber Spaniel', 'Cocker Spaniel',
  'Collie', 'Dachshund', 'Dalmatian', 'Doberman Pinscher', 'English Setter',
  'English Springer Spaniel', 'Field Spaniel', 'Finnish Spitz', 'Flat-Coated Retriever',
  'French Bulldog', 'German Pinscher', 'German Shepherd', 'German Shorthaired Pointer',
  'German Wirehaired Pointer', 'Giant Schnauzer', 'Golden Retriever', 'Gordon Setter',
  'Great Dane', 'Great Pyrenees', 'Greater Swiss Mountain Dog', 'Greyhound', 'Havanese',
  'Irish Red and White Setter', 'Irish Setter', 'Irish Terrier', 'Irish Water Spaniel',
  'Irish Wolfhound', 'Italian Greyhound', 'Jack Russell Terrier', 'Japanese Chin',
  'Keeshond', 'Kerry Blue Terrier', 'Komondor', 'Kuvasz', 'Labrador Retriever',
  'Leonberger', 'Lhasa Apso', 'Maltese', 'Manchester Terrier', 'Mastiff',
  'Miniature Bull Terrier', 'Miniature Pinscher', 'Miniature Schnauzer', 'Neapolitan Mastiff',
  'Newfoundland', 'Norfolk Terrier', 'Norwegian Elkhound', 'Norwich Terrier', 'Old English Sheepdog',
  'Papillon', 'Pekingese', 'Pembroke Welsh Corgi', 'Petit Basset Griffon Vendeen',
  'Pharaoh Hound', 'Plott Hound', 'Pointer', 'Pomeranian', 'Poodle (Miniature)',
  'Poodle (Standard)', 'Poodle (Toy)', 'Portuguese Water Dog', 'Pug', 'Puli',
  'Rhodesian Ridgeback', 'Rottweiler', 'Saint Bernard', 'Saluki', 'Samoyed',
  'Schipperke', 'Scottish Deerhound', 'Scottish Terrier', 'Shetland Sheepdog',
  'Shiba Inu', 'Shih Tzu', 'Siberian Husky', 'Silky Terrier', 'Skye Terrier',
  'Soft Coated Wheaten Terrier', 'Spinone Italiano', 'Staffordshire Bull Terrier',
  'Standard Schnauzer', 'Sussex Spaniel', 'Tibetan Mastiff', 'Tibetan Spaniel',
  'Tibetan Terrier', 'Toy Fox Terrier', 'Vizsla', 'Weimaraner',
  'Welsh Corgi (Cardigan)', 'Welsh Springer Spaniel', 'Welsh Terrier', 'West Highland White Terrier',
  'Whippet', 'Wire Fox Terrier', 'Wirehaired Pointing Griffon', 'Xoloitzcuintli',
  'Yorkshire Terrier', 'Mixed Breed', 'Other'
];
