import { Linking, Pressable, ScrollView, View } from 'react-native';

import { Text } from '@/components/ui/Text';
import { colors } from '@/constants/colors';
import { radii } from '@/constants/radii';
import { spacing } from '@/constants/spacing';

const LAST_UPDATED = 'September 21, 2026';
const SUPPORT_EMAIL = 'support@pawly.app';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <View style={{ gap: spacing.sm }}>
      <Text variant="h2" selectable accessibilityRole="header">
        {title}
      </Text>
      {children}
    </View>
  );
}

function Body({ children }: { children: React.ReactNode }) {
  return (
    <Text variant="body" selectable>
      {children}
    </Text>
  );
}

function Bullet({ children }: { children: React.ReactNode }) {
  return (
    <View style={{ flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }}>
      <View
        style={{
          width: spacing.xs,
          height: spacing.xs,
          borderRadius: radii.full,
          backgroundColor: colors.text.secondary,
          marginTop: spacing.sm,
          marginHorizontal: spacing.sm,
        }}
      />
      <Text variant="body" selectable style={{ flex: 1 }}>
        {children}
      </Text>
    </View>
  );
}

function SupportEmail() {
  return (
    <Pressable
      onPress={() => Linking.openURL(`mailto:${SUPPORT_EMAIL}`)}
      accessibilityRole="link"
      accessibilityLabel={`Email ${SUPPORT_EMAIL}`}
      hitSlop={8}
      style={({ pressed }) => ({ alignSelf: 'flex-start', minHeight: 44, justifyContent: 'center', opacity: pressed ? 0.6 : 1 })}
    >
      <Text variant="bodyStrong" color={colors.accent}>
        {SUPPORT_EMAIL}
      </Text>
    </Pressable>
  );
}

export default function TermsOfServiceScreen() {
  return (
    <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ padding: spacing.lg, gap: spacing.xl }}>
      <Text variant="caption">Last updated {LAST_UPDATED}</Text>

      <Body>
        Welcome to Pawly. By downloading or using this app, you agree to be bound by these terms of service ("Terms").
        Please read them carefully before using Pawly. If you do not agree to these Terms, do not use the app.
      </Body>

      <Section title="1. Acceptance of terms">
        <Body>
          By creating an account or using any feature of Pawly, you confirm that you are at least 13 years old, have the
          legal capacity to enter into these Terms and agree to comply with them. If you are under the age of majority
          where you live, a parent or guardian must agree to these Terms for you. If you use Pawly on behalf of an
          organization, you represent that you have authority to bind that organization to these Terms.
        </Body>
      </Section>

      <Section title="2. Description of service">
        <Body>
          Pawly is a dog training app that provides personalized plans, a coach, a live coach that uses your camera,
          progress tracking and guides. It is designed to help dog owners train their dogs. Pawly does not replace
          professional veterinary care or certified dog training services.
        </Body>
      </Section>

      <Section title="3. Not professional advice">
        <Body>
          The plans, coach responses and content in Pawly are for informational and educational purposes only. They do
          not constitute professional veterinary, behavioral or certified dog training advice.
        </Body>
        <Body>
          Dogs with aggression, severe anxiety or complex behavioral issues should be evaluated by a licensed
          veterinarian or certified professional dog trainer. Pawly is not liable for any injury, harm or damage to you,
          your dog, third parties or property arising from reliance on app content or training suggestions.
        </Body>
      </Section>

      <Section title="4. AI-generated content">
        <Body>
          The coach, the live coach, your plan and the way it adapts are generated by AI. AI-generated content may be
          inaccurate, incomplete or wrong for your dog, and the live coach can misread what the camera sees.
        </Body>
        <Bullet>It is not veterinary or behavioral-medicine advice, and it does not diagnose or treat any condition.</Bullet>
        <Bullet>
          If your dog has bitten or tried to bite, guards food or objects with growling or snapping, or shows other
          aggression, stop training on your own and consult a certified behaviorist or a veterinary behaviorist.
        </Bullet>
        <Bullet>A sudden change in behavior can be a sign of pain or illness. See your vet.</Bullet>
        <Bullet>In an emergency, such as an injury, suspected poisoning, heatstroke or trouble breathing, contact your vet or an emergency animal hospital right away. Do not wait for an answer from the app.</Bullet>
        <Body>
          You are responsible for your dog, for the people and animals around you, and for deciding whether a suggestion
          is safe in your situation. You can report a coach answer you think is wrong or unsafe from the chat.
        </Body>
      </Section>

      <Section title="5. User accounts">
        <Body>
          You are responsible for keeping your account credentials confidential and for all activity under your account.
          You agree to:
        </Body>
        <Bullet>Provide accurate and complete registration information.</Bullet>
        <Bullet>Keep your password secure and tell us immediately about unauthorized access.</Bullet>
        <Bullet>Not share your account with others or create accounts on behalf of third parties.</Bullet>
        <Body>
          We may suspend or terminate accounts that violate these Terms or that we reasonably believe have been
          compromised.
        </Body>
      </Section>

      <Section title="6. User content">
        <Body>
          You may add photos, messages and other content ("User Content") to Pawly. By adding content, you grant Pawly a
          non-exclusive, royalty-free, worldwide license to store, process and display that content solely to provide
          the service to you, including sending it to the service providers named in the privacy policy.
        </Body>
        <Body>You agree not to add content that:</Body>
        <Bullet>Depicts animal abuse, cruelty or illegal activity.</Bullet>
        <Bullet>Contains personal information of third parties without their consent.</Bullet>
        <Bullet>Infringes third-party intellectual property rights.</Bullet>
        <Bullet>Is obscene, defamatory or otherwise objectionable.</Bullet>
        <Body>We may remove content that violates these Terms without prior notice.</Body>
      </Section>

      <Section title="7. Acceptable use">
        <Body>You agree to use Pawly only for lawful purposes, and you will not:</Body>
        <Bullet>Use Pawly to train a dog with pain, fear or intimidation, or in any way that harms an animal.</Bullet>
        <Bullet>Attempt to reverse-engineer, decompile or disassemble any part of the app.</Bullet>
        <Bullet>Use automated tools to scrape, crawl or extract data from the app.</Bullet>
        <Bullet>Circumvent security, authentication, usage limits or subscription checks.</Bullet>
        <Bullet>Try to make the coach produce harmful, unlawful or abusive content, or use it for anything other than training your own dog.</Bullet>
        <Bullet>Point the live coach camera at people who have not agreed to be in view.</Bullet>
        <Bullet>Transmit malware, spam or any harmful code.</Bullet>
        <Bullet>Use the app in any way that could damage, disable or impair the service.</Bullet>
      </Section>

      <Section title="8. Intellectual property">
        <Body>
          All content, design, code, logos and materials in Pawly, other than User Content, are owned by or licensed to
          Pawly and protected by intellectual property laws. You may not copy, reproduce, distribute or create derivative
          works from Pawly's content without our express written permission.
        </Body>
      </Section>

      <Section title="9. Subscriptions and payments">
        <Body>
          Pawly is free to use with limits. Pawly Pro is an optional auto-renewing subscription, offered monthly or
          yearly, that removes those limits.
        </Body>
        <Bullet>Price: the price and billing period are shown in the app before you buy. Prices can differ by country and may include tax.</Bullet>
        <Bullet>Billing: payment is charged to your Apple Account when you confirm the purchase. Apple processes the payment; we never see your card details.</Bullet>
        <Bullet>Renewal: the subscription renews automatically for the same period and price unless you cancel at least 24 hours before the end of the current period. Your account is charged for renewal within 24 hours before the period ends.</Bullet>
        <Bullet>Free trial: if a free trial is offered, it converts to a paid subscription when it ends unless you cancel at least 24 hours before then. Any unused part of a trial is forfeited when you buy a subscription.</Bullet>
        <Bullet>Managing and cancelling: manage or cancel your subscription in your App Store account settings, under Subscriptions. Deleting the app or your Pawly account does not cancel it. After you cancel, Pro stays active until the end of the period you paid for.</Bullet>
        <Bullet>Refunds: we do not issue refunds ourselves. Apple handles all billing and refund requests, at reportaproblem.apple.com, under its own policies. Nothing in these Terms limits refund rights you have under the law where you live.</Bullet>
        <Bullet>Restoring: if you reinstall the app or change devices, choose Restore purchases on the Pawly Pro screen.</Bullet>
        <Bullet>Price changes: if the price changes, Apple will notify you, and where required ask for your consent, before it applies to you.</Bullet>
        <Body>Purchases are also subject to Apple's terms. If Pawly is offered on another store, that store's billing terms apply in the same way.</Body>
      </Section>

      <Section title="10. Termination">
        <Body>
          You can delete your account at any time from Profile by choosing Delete account. We may suspend or terminate
          your account for violations of these Terms, without notice and without liability to you.
        </Body>
        <Body>
          On termination, your right to use the app ends immediately. Cancel any subscription with Apple separately.
          Sections that by their nature should survive (Not professional advice, AI-generated content, Limitation of
          liability, Disclaimer of warranties, Governing law) survive termination.
        </Body>
      </Section>

      <Section title="11. Limitation of liability">
        <Body>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, PAWLY AND ITS AFFILIATES, OFFICERS, EMPLOYEES AND AGENTS SHALL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OR
          INABILITY TO USE THE APP, INCLUDING ANY INJURY OR DAMAGE TO YOU, YOUR DOG OR THIRD PARTIES, AND INCLUDING
          RELIANCE ON AI-GENERATED CONTENT.
        </Body>
        <Body>
          OUR TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE APP IS LIMITED TO THE AMOUNT YOU PAID FOR PAWLY IN THE 12
          MONTHS BEFORE THE CLAIM.
        </Body>
        <Body>
          IN JURISDICTIONS THAT DO NOT ALLOW EXCLUSION OF CERTAIN WARRANTIES OR LIMITATION OF LIABILITY, OUR LIABILITY IS
          LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW. NOTHING IN THESE TERMS LIMITS LIABILITY THAT CANNOT BE LIMITED
          BY LAW.
        </Body>
      </Section>

      <Section title="12. Disclaimer of warranties">
        <Body>
          PAWLY IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
          INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
          NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE OR FREE OF VIRUSES OR OTHER
          HARMFUL COMPONENTS, OR THAT ANY TRAINING RESULT WILL BE ACHIEVED.
        </Body>
      </Section>

      <Section title="13. Apple">
        <Body>
          These Terms are between you and Pawly, not Apple. Apple is not responsible for the app or its content, has no
          obligation to provide maintenance or support for it, and is a third-party beneficiary of these Terms with the
          right to enforce them against you. Your use of the app must also comply with the App Store terms of service.
        </Body>
      </Section>

      <Section title="14. Governing law">
        <Body>
          These Terms are governed by the laws of the jurisdiction where the developer resides, without regard to its
          conflict of law provisions. If you are a consumer, you also keep the protection of the mandatory laws of the
          country where you live.
        </Body>
      </Section>

      <Section title="15. Changes to these terms">
        <Body>
          We may update these Terms from time to time. We notify you of material changes by showing a notice in the app
          and updating the date above. Continued use of the app after changes means you accept the revised Terms.
        </Body>
      </Section>

      <Section title="16. Contact">
        <Body>If you have questions about these Terms, email Pawly support.</Body>
        <SupportEmail />
      </Section>
    </ScrollView>
  );
}
