-- Learn library: 20 more articles.
-- Same shape and conventions as 20260317110200_seed_articles.sql.
-- Content blocks: paragraph, heading (level 2 or 3), bullets, checklist, tip, warning.
-- All methods are reward-based. Medical topics defer to a veterinarian.

insert into public.articles (
  slug,
  title,
  excerpt,
  content,
  category,
  difficulty,
  read_time_minutes,
  is_featured,
  is_published,
  cover_image_url,
  tags,
  sort_order
)
values
  (
    'puppy-socialization-a-checklist-for-the-early-weeks',
    'Puppy Socialization: A Checklist for the Early Weeks',
    'Socialization is not about meeting everyone. It is about calm, positive exposure to the world while your puppy is most open to it.',
    $$[
      {"type":"paragraph","text":"Puppies go through a sensitive period, roughly from 3 to 14 weeks of age, when new experiences are absorbed more easily than they ever will be again. What your puppy meets calmly now tends to feel normal later. What they never meet, or meet in a frightening way, can become a worry."},
      {"type":"heading","level":2,"text":"Quality matters more than quantity"},
      {"type":"paragraph","text":"Good socialization means your puppy notices something new, stays relaxed enough to eat and explore, and leaves feeling fine. It does not mean being passed around a crowd or pushed toward things that scare them. Let the puppy choose to approach, and pair new things with food or play."},
      {"type":"heading","level":2,"text":"What to cover"},
      {"type":"checklist","items":["People of different ages, sizes, and voices, including hats, beards, sunglasses, and uniforms","Surfaces such as grass, gravel, metal grates, wet ground, and slippery floors","Sounds such as traffic, vacuum cleaners, doorbells, and recorded fireworks at low volume","Gentle handling of paws, ears, mouth, and collar","Calm, vaccinated, puppy-friendly adult dogs","Car rides, the vet lobby, and the grooming table, with treats and no procedures","Wheels and movement such as bikes, strollers, skateboards, and joggers at a distance","Short periods alone in a safe space"]},
      {"type":"heading","level":2,"text":"Staying safe before vaccines are finished"},
      {"type":"bullets","items":["Carry your puppy or use a blanket in places where unknown dogs have been","Choose a well-run puppy class that checks vaccination records and cleans the floor","Meet known, healthy, vaccinated dogs in private yards","Avoid dog parks and busy pet store floors for now"]},
      {"type":"tip","text":"Watch your puppy, not the checklist. One relaxed minute near a new thing is worth more than ten tense ones. If they hang back, add distance and let them watch."},
      {"type":"warning","text":"Disease risk varies by region. Ask your veterinarian which outings are sensible for your puppy at each stage of the vaccine schedule."},
      {"type":"paragraph","text":"The window does not slam shut, and older puppies and adult dogs can still learn that new things are safe. It simply takes more time. Use these early weeks well, keep every exposure short and pleasant, and you give your dog a wide comfort zone for life."}
    ]$$::jsonb,
    'Puppy Training',
    'beginner',
    6,
    true,
    true,
    null,
    array['puppy','socialization','checklist'],
    15
  ),
  (
    'your-puppys-first-week-home',
    'Your Puppy''s First Week Home',
    'The first week is for safety, sleep, and routine. Training cues can wait a few days. Feeling secure cannot.',
    $$[
      {"type":"paragraph","text":"A new puppy has just lost their litter, their mother, and every smell they knew. The most useful thing you can do in week one is make life predictable. Skills come quickly once a puppy feels safe."},
      {"type":"heading","level":2,"text":"Set up before the puppy arrives"},
      {"type":"checklist","items":["A pen or gated puppy-safe area with a bed and water","A crate sized so the puppy can stand, turn, and lie flat","Chew items in every room you use","An enzymatic cleaner for accidents","The food the breeder or shelter was feeding, to avoid a sudden diet change","A first vet appointment booked for the first few days"]},
      {"type":"heading","level":2,"text":"A simple daily rhythm"},
      {"type":"bullets","items":["Potty trip after waking, after eating, after play, and at least every hour when awake","Short play or exploring, then a calm chew","Nap in the pen or crate. Young puppies need 16 to 20 hours of sleep a day","Meals at the same times each day","Last potty trip right before bed"]},
      {"type":"heading","level":2,"text":"The first nights"},
      {"type":"paragraph","text":"Put the crate or pen next to your bed for the first week or two. A puppy who can hear and smell you settles faster, and you will hear them stir when they need to go out. Night potty trips should be quiet and boring: out, praise, back to bed. You can move the crate gradually once nights are calm."},
      {"type":"tip","text":"Start name and reward games on day one if your puppy is keen, but keep them to a minute or two. Hand-feeding part of a meal is an easy way to build trust."},
      {"type":"warning","text":"Most wild biting and zooming in the evening is an overtired puppy. Before you add more exercise, try a potty trip and a nap."},
      {"type":"paragraph","text":"Limit visitors for the first few days, keep outings short, and do not worry about teaching everything at once. A puppy who eats, sleeps, toilets outside most of the time, and chooses to be near you is having an excellent first week."}
    ]$$::jsonb,
    'Puppy Training',
    'beginner',
    6,
    false,
    true,
    null,
    array['puppy','first week','routine'],
    16
  ),
  (
    'a-house-training-schedule-by-age',
    'A House-Training Schedule by Age',
    'House training is mostly a timing problem. Match the schedule to what a puppy of that age can physically manage.',
    $$[
      {"type":"paragraph","text":"Puppies do not have accidents out of spite. They have small bladders, late warning signals, and no idea that carpet is different from grass. Your job is to get them to the right place often enough that going there becomes the habit."},
      {"type":"heading","level":2,"text":"The moments that always need a trip"},
      {"type":"checklist","items":["Right after waking, including after naps","Within 5 to 15 minutes of eating or a big drink","During and after play or excitement","After coming out of the crate or pen","Before bed and first thing in the morning"]},
      {"type":"heading","level":2,"text":"Rough daytime gaps while awake"},
      {"type":"bullets","items":["8 to 10 weeks: every 30 to 60 minutes","10 to 12 weeks: every 1 to 2 hours","3 to 4 months: every 2 to 3 hours","4 to 6 months: every 3 to 4 hours","Over 6 months: most dogs manage 4 to 6 hours, with accidents becoming rare"]},
      {"type":"paragraph","text":"These are starting points, not guarantees. Small breeds often need shorter gaps for longer. If accidents are happening, shorten the gap rather than waiting for the puppy to ask."},
      {"type":"heading","level":2,"text":"Make each trip count"},
      {"type":"bullets","items":["Go out with your puppy, on leash, to the same spot","Stand still and stay boring until they go","Mark and treat the moment they finish, right there, not back at the door","Add a few minutes of play or sniffing afterward so going quickly pays off","Supervise or confine between trips so there is no chance to rehearse indoors"]},
      {"type":"tip","text":"Keep a simple log for one week. Most puppies show a pattern, and the pattern tells you when to go out before the accident happens."},
      {"type":"warning","text":"Never scold or rub a nose in an accident. It teaches the puppy to hide from you when they need to go. Interrupt gently, head outside, and clean with an enzymatic cleaner."},
      {"type":"paragraph","text":"Frequent small puddles, straining, blood, a sudden increase in drinking, or accidents in a dog who was reliably trained all deserve a call to your veterinarian before you treat it as a training problem."}
    ]$$::jsonb,
    'Puppy Training',
    'beginner',
    6,
    false,
    true,
    null,
    array['potty training','puppy','schedule'],
    17
  ),
  (
    'adolescent-regression-when-your-teenage-dog-forgets-everything',
    'Adolescent Regression: When Your Teenage Dog Forgets Everything',
    'Between roughly 6 and 18 months, many dogs get more distractible and less responsive. It is a developmental phase, and it passes.',
    $$[
      {"type":"paragraph","text":"Your puppy came when called, sat politely, and settled in the evening. Then somewhere around six to eight months the recall vanished and the pulling came back. This is adolescence. The brain is reorganizing, hormones are changing, and the outside world has become far more interesting than it used to be."},
      {"type":"heading","level":2,"text":"What is normal"},
      {"type":"bullets","items":["Slower responses to cues that used to be quick","More interest in dogs, smells, and movement","Bursts of excitability and lower frustration tolerance","Testing fences, counters, and boundaries that were never an issue","Brief spells of new caution toward familiar things"]},
      {"type":"paragraph","text":"Large breeds can stay in this phase until two years or later. Research on pet dogs has found a dip in responsiveness to the main caregiver at around eight months, which then recovers. It is not defiance, and it is not a sign that your early training failed."},
      {"type":"heading","level":2,"text":"What helps"},
      {"type":"checklist","items":["Go back a stage in your training and pay well for easy wins","Use a long line so recall cannot fail while it is wobbly","Raise the value of rewards outdoors","Manage the environment: gates, leashes, and clear counters","Keep sessions short and end while your dog is still succeeding","Give daily outlets such as sniffing walks, chewing, and play","Protect sleep. Adolescents still need plenty of it"]},
      {"type":"tip","text":"If a familiar object suddenly worries your dog, stay relaxed, add distance, and let them investigate at their own pace. Pair it with food. Do not pull them toward it."},
      {"type":"warning","text":"This is the age when many owners switch to harsher methods out of frustration. Corrections at this stage tend to damage trust and can create fear or reactivity that outlasts adolescence."},
      {"type":"paragraph","text":"Consistency through this phase pays off. The skills are still in there. Keep reinforcing them at a level your dog can manage, and they return stronger as the brain matures."}
    ]$$::jsonb,
    'Puppy Training',
    'intermediate',
    6,
    false,
    true,
    null,
    array['adolescence','regression','teenage dog'],
    18
  ),
  (
    'reading-dog-body-language-the-early-stress-signals',
    'Reading Dog Body Language: The Early Stress Signals',
    'Dogs say they are uncomfortable long before they growl. Learning the quiet signals lets you help earlier.',
    $$[
      {"type":"paragraph","text":"Most dogs give many small signals before they bark, lunge, or snap. These signals are easy to miss because they are brief and look ordinary. Once you can see them, you can change the situation before your dog feels the need to get louder."},
      {"type":"heading","level":2,"text":"Early signs of unease"},
      {"type":"checklist","items":["Lip licking or tongue flicks when no food is around","Yawning when not tired","Turning the head or whole body away","Whale eye, where the white of the eye shows in a crescent","Ears pinned back or held tight","A closed, tense mouth in a dog who was panting loosely a moment ago","Lifting one front paw","Sudden sniffing of the ground or scratching","A full-body shake-off after an interaction"]},
      {"type":"heading","level":2,"text":"Signs the pressure is rising"},
      {"type":"bullets","items":["Freezing or going very still","Stiff body with weight shifted forward or back","Tail held high and tight, or tucked under","Hard stare","Refusing food they would normally take","Lip lift, growl, or air snap"]},
      {"type":"paragraph","text":"Read the whole dog and the context, not one signal. A yawn at bedtime means nothing. A yawn, a head turn, and a lip lick while a child hugs the dog means the dog wants the hug to stop."},
      {"type":"heading","level":2,"text":"Common misreadings"},
      {"type":"bullets","items":["A wagging tail is not always friendly. A high, stiff, fast wag often signals arousal or tension","A dog who rolls over is not always asking for a belly rub. A tense roll with a tucked tail is an appeal for space","A dog who looks guilty is usually showing appeasement in response to your tone, not understanding of what they did"]},
      {"type":"tip","text":"When you see early signals, give your dog an out. Add distance, end the interaction, or lower the difficulty. Dogs who learn that quiet signals work have less need for loud ones."},
      {"type":"warning","text":"Never punish a growl. A growl is a warning, and a dog who is punished for warning may learn to skip it. Thank the information, create space, and get help from a qualified professional if growling is frequent."},
      {"type":"paragraph","text":"Relaxed dogs look loose: soft eyes, wiggly body, open mouth, weight evenly balanced. Learn your own dog's relaxed picture first. It makes every change from it easier to spot."}
    ]$$::jsonb,
    'Handler Skills',
    'beginner',
    7,
    true,
    true,
    null,
    array['body language','stress signals','safety'],
    19
  ),
  (
    'reward-hierarchy-choosing-the-right-treat-for-the-job',
    'Reward Hierarchy: Choosing the Right Treat for the Job',
    'Not all rewards are equal to your dog. Rank them, then match the pay to the difficulty of the work.',
    $$[
      {"type":"paragraph","text":"If your dog works happily for kibble in the kitchen and ignores it at the park, the kibble has not stopped working. The job got harder and the pay stayed the same. A reward hierarchy fixes that mismatch."},
      {"type":"heading","level":2,"text":"Find your dog's ranking"},
      {"type":"paragraph","text":"Offer two options in closed hands, let your dog sniff both, and see which one they choose. Repeat across a few days with different foods. Your dog decides what is valuable, not the price on the bag."},
      {"type":"bullets","items":["Low value: regular kibble, plain dry biscuits","Medium value: soft commercial training treats, a different brand of kibble","High value: cooked chicken, cheese, freeze-dried liver, fish","Non-food: tug, a thrown toy, a chance to sniff, permission to go greet"]},
      {"type":"heading","level":2,"text":"Match pay to difficulty"},
      {"type":"checklist","items":["Known skill in a quiet room: low value is fine","New skill, or known skill in a new place: medium to high","Recall, distractions, vet visits, scary things: the best you have","A breakthrough moment: several treats in a row, one at a time"]},
      {"type":"heading","level":2,"text":"Practical details"},
      {"type":"bullets","items":["Cut treats to the size of a pea, smaller for small dogs","Choose soft treats that can be swallowed fast so the session keeps moving","Count training food as part of the daily ration and reduce meals to match","Mix values in your pouch so your dog never knows which one is coming"]},
      {"type":"tip","text":"If your dog will not take a food they normally love, that is useful information. They are usually too stressed, too excited, or too full. Make the situation easier before you reach for a better treat."},
      {"type":"warning","text":"Never use grapes, raisins, chocolate, macadamia nuts, onions, or anything sweetened with xylitol, also labelled birch sugar. Dogs with allergies, pancreatitis, or weight concerns need treats approved by their veterinarian."},
      {"type":"paragraph","text":"A good reward system is flexible. Pay generously when the work is hard, thin it out when the skill is easy, and keep a few favorites in reserve for the moments that matter most."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    5,
    false,
    true,
    null,
    array['rewards','treats','motivation'],
    20
  ),
  (
    'trigger-stacking-and-why-your-dog-needs-rest-days',
    'Trigger Stacking and Why Your Dog Needs Rest Days',
    'A dog who copes with one stressor can fall apart on the third. Stress adds up, and it takes time to drain.',
    $$[
      {"type":"paragraph","text":"Your dog walked past a barking dog on Monday without trouble. On Thursday a calmer dog at the same distance caused an explosion. Often the difference is not the trigger. It is everything that happened before it."},
      {"type":"heading","level":2,"text":"How stacking works"},
      {"type":"paragraph","text":"Each stressful or highly exciting event raises your dog's arousal. If the next event arrives before they have come back down, the second one lands on top of the first. After enough layers, something small tips the dog over threshold. Recovery can take hours, and after a big scare it may take a day or more."},
      {"type":"heading","level":2,"text":"Things that add to the stack"},
      {"type":"bullets","items":["A vet or grooming visit","Visitors, workmen, or a noisy household","Close passes with dogs or people on walks","Thunder, fireworks, or construction noise","Poor sleep or a disrupted routine","Pain, itching, or an upset stomach","Very intense play, including long ball-chasing sessions"]},
      {"type":"heading","level":2,"text":"What a rest day looks like"},
      {"type":"checklist","items":["Skip the usual trigger-heavy walk","Offer a garden sniff, a quiet field on a long line, or indoor scent games","Feed from scatter feeding, lick mats, or food puzzles","Provide a long-lasting chew","Protect uninterrupted sleep","Keep training to a few easy wins, or none"]},
      {"type":"tip","text":"Keep brief notes on hard days and what came before them. Patterns show up quickly, and they tell you when to plan an easier day in advance."},
      {"type":"warning","text":"If your dog's tolerance drops suddenly with no clear cause, book a vet check. Pain is one of the most common hidden contributors to reactivity."},
      {"type":"paragraph","text":"Rest days are not lost training days. A dog who starts the week with an empty stress bucket learns faster and recovers quicker than one who is always running close to full."}
    ]$$::jsonb,
    'Reactivity',
    'intermediate',
    5,
    false,
    true,
    null,
    array['trigger stacking','stress','rest days'],
    21
  ),
  (
    'decompression-walks-let-your-dog-sniff',
    'Decompression Walks: Let Your Dog Sniff',
    'Not every walk needs to be a training session or a workout. A slow, sniffy walk in a quiet place is one of the best things you can offer.',
    $$[
      {"type":"paragraph","text":"A decompression walk is a walk where your dog sets the pace and follows their nose, in a place quiet enough that neither of you has to be on guard. Sniffing is how dogs gather information, and long bouts of it tend to lower arousal rather than raise it."},
      {"type":"heading","level":2,"text":"What you need"},
      {"type":"checklist","items":["A quiet natural space such as a field, woodland edge, or empty sports ground","A well-fitted harness with a back clip","A long line of 10 to 30 feet, or safe legal off-leash access if your recall is solid","Twenty minutes or more with no schedule"]},
      {"type":"heading","level":2,"text":"How to do it"},
      {"type":"bullets","items":["Let your dog choose the direction and the speed","Stop when they stop. Let them finish each sniff","Keep the line loose and out from under their legs","Stay quiet. Few cues, no drills","Quietly reward any check-in your dog offers, then let them go back to sniffing"]},
      {"type":"heading","level":2,"text":"Long line safety"},
      {"type":"bullets","items":["Always clip a long line to a harness, never to a collar","Wear gloves if your dog is strong, and do not wrap the line around your hand","Gather slack as your dog comes toward you so nobody gets tangled","Avoid long lines near roads, cyclists, or crowded paths"]},
      {"type":"tip","text":"No countryside nearby? Try an empty car park at dawn, a quiet cemetery where dogs are allowed, or an industrial estate on a Sunday. Quiet matters more than scenery."},
      {"type":"warning","text":"A decompression walk stops being one if your dog is scanning for triggers the whole time. If the location keeps producing surprises, find a different one."},
      {"type":"paragraph","text":"Two or three of these a week can make a visible difference to a busy, reactive, or adolescent dog. They also help on leash: a dog whose need to sniff is met pulls less to get to smells on ordinary walks."}
    ]$$::jsonb,
    'Leash Walking',
    'beginner',
    5,
    false,
    true,
    null,
    array['decompression','sniffing','long line'],
    22
  ),
  (
    'enrichment-on-a-budget',
    'Enrichment on a Budget',
    'Mental work tires dogs in a way that more running does not. Most of it can be made from things already in your recycling.',
    $$[
      {"type":"paragraph","text":"Enrichment gives your dog a legal outlet for things dogs need to do: sniff, forage, chew, shred, lick, and solve problems. Ten minutes of it often settles a dog better than another lap of the block, and it does not need to cost anything."},
      {"type":"heading","level":2,"text":"Free or nearly free ideas"},
      {"type":"checklist","items":["Scatter feeding: toss part of a meal across grass or a rug","Towel roll: lay kibble along a towel, roll it up, and let your dog unroll it","Muffin tin: kibble in the cups, tennis balls on top","Box of boxes: treats inside nested cardboard boxes and paper packing","Cardboard tube: fold the ends over a few treats","Frozen lick: wet food or plain yogurt smeared in a bowl or on a mat and frozen","Find it: hide treats around one room while your dog waits, then release them to search","A new route: walk somewhere different and let them sniff"]},
      {"type":"heading","level":2,"text":"Match the activity to the need"},
      {"type":"bullets","items":["Licking and chewing tend to calm. Use them before guests arrive or at settle time","Sniffing and foraging tire the brain. Use them on rest days or bad-weather days","Shredding is a good outlet for dogs who destroy things when bored","Puzzles build confidence when the first few are easy"]},
      {"type":"tip","text":"Start easy. If a puzzle is too hard, many dogs give up or get frustrated. Leave the box open and the towel loose at first, then make it harder over a few days."},
      {"type":"warning","text":"Supervise anything homemade. Remove tape, staples, and string. Skip shredding games for dogs who swallow cardboard or fabric, and check that peanut butter contains no xylitol."},
      {"type":"paragraph","text":"Feed at least one meal a day from something other than a bowl and you have added enrichment without adding calories or cost. Dogs who guard food from people or other pets should do these activities alone, in a separate space."}
    ]$$::jsonb,
    'Settling',
    'beginner',
    5,
    false,
    true,
    null,
    array['enrichment','mental exercise','budget'],
    23
  ),
  (
    'preparing-for-the-vet-cooperative-care-basics',
    'Preparing for the Vet: Cooperative Care Basics',
    'Vet visits go better when your dog has practiced the pieces at home and has a say in the process.',
    $$[
      {"type":"paragraph","text":"Cooperative care means teaching your dog to take part in handling rather than simply being held for it. Dogs who know what is coming, and who can ask for a pause, struggle less and recover faster. You do not need to train a full routine to see a difference."},
      {"type":"heading","level":2,"text":"Three skills worth having"},
      {"type":"bullets","items":["Chin rest: your dog rests their chin on your palm or a towel and holds it there. Chin down means carry on. Chin up means pause","Stationing on a mat: a familiar mat gives your dog a known place to stand or lie on the exam table or floor","Consent to touch: touch a body part, then treat. Work from shoulders toward paws, ears, and tail"]},
      {"type":"heading","level":2,"text":"Practice at home"},
      {"type":"checklist","items":["Look in ears and lift lips for one second, then treat","Hold a paw and press gently on each toe","Run your hands along the belly and back legs","Rest an object on the chest to mimic a stethoscope","Hold gently around the shoulders for two seconds, then release and treat","Stop as soon as your dog pulls away, and make the next rep easier"]},
      {"type":"heading","level":2,"text":"Make the clinic familiar"},
      {"type":"bullets","items":["Ask whether you can drop in for happy visits: walk in, treats, step on the scale, leave","Bring high-value food and your dog's mat","Wait in the car or outside if the lobby is crowded","Ask staff to go slowly and tell them what your dog finds hard","Look for clinics with low-stress or fear-free handling training"]},
      {"type":"tip","text":"Feed during the procedure, not only after. A steady stream of something lickable while the vet works changes how the whole event feels."},
      {"type":"warning","text":"If your dog panics, freezes, or has tried to bite at the vet, talk to your veterinarian before the next appointment. Pre-visit medication and a muzzle your dog has been trained to enjoy are kind, sensible options."},
      {"type":"paragraph","text":"Even a few minutes of handling practice each week adds up. The goal is a dog who treats an exam as a familiar, well-paid routine rather than something that happens to them."}
    ]$$::jsonb,
    'Handler Skills',
    'intermediate',
    6,
    false,
    true,
    null,
    array['cooperative care','vet visits','handling'],
    24
  ),
  (
    'nail-trims-without-a-fight',
    'Nail Trims Without a Fight',
    'Most dogs who hate nail trims were rushed once. Go back to the start, break it into small pieces, and let the dog set the pace.',
    $$[
      {"type":"paragraph","text":"Nails are sensitive, paws are vulnerable, and one painful clip can set a dog against the whole process for years. The fix is slow and unglamorous: rebuild each piece of the routine until it predicts food instead of worry."},
      {"type":"heading","level":2,"text":"Break it into steps"},
      {"type":"checklist","items":["The clippers or grinder appear, then a treat appears","Touch the tool to a shoulder, then treat","Hold a paw for one second, then treat","Touch the tool to a nail without cutting, then treat","Clip the tip of one nail, then pay with several treats","For grinders: run it at a distance first, then nearer, then touch the handle to the paw while it runs"]},
      {"type":"paragraph","text":"Stay on each step until your dog is relaxed and looking for the treat. That might take one session or ten. If your dog pulls the paw away, let it go, and make the next repetition easier."},
      {"type":"heading","level":2,"text":"Make it easier on both of you"},
      {"type":"bullets","items":["One nail a day is a perfectly good plan","Take off thin slivers rather than one big cut, and stop before the quick","On dark nails, stop when you see a pale oval with a dark dot in the center of the cut surface","Keep tools sharp. Dull clippers crush instead of cutting","Use good light and have styptic powder within reach","Try a lick mat at nose height once your dog is comfortable with the basics"]},
      {"type":"tip","text":"A scratch board, which is sandpaper fixed to a board, lets many dogs file their own front nails. Teach a paw swipe on it and reward each scratch."},
      {"type":"warning","text":"If your dog growls, snaps, or panics, stop. Do not pin them down to finish. Ask your veterinarian or a fear-free groomer for help, and ask whether medication is appropriate while you retrain."},
      {"type":"paragraph","text":"If the nails are already long, have a professional take them back while you rebuild the routine at home. Overgrown nails change how a dog stands and can be painful, so it is worth getting them comfortable with the process."}
    ]$$::jsonb,
    'Handler Skills',
    'intermediate',
    5,
    false,
    true,
    null,
    array['nail trims','grooming','cooperative care'],
    25
  ),
  (
    'introducing-a-new-dog-to-your-resident-dog',
    'Introducing a New Dog to Your Resident Dog',
    'First meetings go best outdoors, in motion, and slowly. The first few weeks at home matter just as much as the first hello.',
    $$[
      {"type":"paragraph","text":"Most dogs can learn to share a home, but few enjoy a stranger appearing in their living room. A careful introduction costs a little time and avoids a bad first impression that can take months to undo."},
      {"type":"heading","level":2,"text":"The first meeting"},
      {"type":"checklist","items":["Choose neutral ground, such as a quiet street or field, not your home or yard","One handler per dog, both dogs on loose leashes","Start with a parallel walk, far enough apart that both dogs can relax","Close the gap gradually as body language stays loose","Allow a brief sniff of three seconds or so, then cheerfully call the dogs apart and walk on","Repeat short greetings. Keep moving between them"]},
      {"type":"heading","level":2,"text":"Coming home"},
      {"type":"bullets","items":["Pick up toys, chews, and food bowls before both dogs enter","Walk in together after the outdoor meeting, resident dog first if they are relaxed","Let the new dog explore while the resident dog is occupied elsewhere, then swap","Feed in separate rooms or behind gates","Give each dog their own bed, water, and resting area"]},
      {"type":"heading","level":2,"text":"The first weeks"},
      {"type":"bullets","items":["Supervise all time together and separate the dogs when you cannot watch","Interrupt play that gets one-sided or frantic, and give both dogs a break","Keep one-on-one time with each dog every day","Protect the older or quieter dog's rest, especially from a puppy","Do not leave the dogs alone together until you have seen weeks of relaxed behavior"]},
      {"type":"tip","text":"Good signs include loose curved bodies, play bows, taking turns, and both dogs choosing to disengage and sniff. Stiffness, hard staring, or one dog repeatedly trying to leave means add distance."},
      {"type":"warning","text":"Tight leashes and face-to-face greetings in doorways create tension. If there is a fight, or one dog is consistently guarding or bullying, separate them and contact a qualified behavior professional."},
      {"type":"paragraph","text":"Friendship is not required on day one. Calm coexistence is the first goal. Many pairs take several weeks to settle, and managing space generously during that time is what lets a good relationship form."}
    ]$$::jsonb,
    'Basics',
    'intermediate',
    6,
    false,
    true,
    null,
    array['new dog','introductions','multi-dog home'],
    26
  ),
  (
    'dogs-and-kids-safety-rules-for-the-whole-family',
    'Dogs and Kids: Safety Rules for the Whole Family',
    'Most bites to children come from a familiar dog at home. Clear rules and active supervision prevent nearly all of them.',
    $$[
      {"type":"paragraph","text":"Children move fast, make sudden noises, and hug with their faces close. Many dogs tolerate this rather than enjoy it, and tolerance runs out. Keeping everyone safe is an adult job. It cannot be left to the child or the dog."},
      {"type":"heading","level":2,"text":"Rules for children"},
      {"type":"checklist","items":["Leave the dog alone when they are eating, chewing, sleeping, or in their bed or crate","No hugging, kissing, climbing on, or riding the dog","Call the dog over instead of walking up to them. If the dog does not come, the answer is no","Pet with one hand on the shoulder or chest for three seconds, then stop and see whether the dog asks for more","If a dog chases or jumps, stand still like a tree with arms folded and look at your feet","Always ask the adult, then the dog, before touching a dog you do not know"]},
      {"type":"heading","level":2,"text":"Rules for adults"},
      {"type":"bullets","items":["Supervise actively: eyes on, close enough to step in. Being in the same house is not supervision","When you cannot supervise, separate with a gate, pen, crate, or closed door","Give the dog a retreat space that children never enter","Learn the early stress signals: lip licking, yawning, turning away, whale eye, stiffening","Step in at the first signal, not the growl"]},
      {"type":"heading","level":2,"text":"Build good experiences"},
      {"type":"bullets","items":["Let children toss treats, help fill food puzzles, or play fetch with an adult nearby","Teach simple cues together so the child has a calm way to interact","Keep play low and slow. No chase games between dogs and small children","Give the dog quiet time after busy family periods"]},
      {"type":"tip","text":"Crawling babies and toddlers are the highest-risk age because they approach resting dogs and cannot follow rules. Gates and pens are the most reliable tool during these years."},
      {"type":"warning","text":"If your dog growls at, stiffens around, or avoids a child, do not punish the dog. Separate them, keep them separated, and contact a veterinary behaviorist or certified behavior consultant promptly."},
      {"type":"paragraph","text":"Dogs and children can be wonderful together. That relationship is built on the dog having choices and the adults making sure both sides are never put in a position to fail."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    6,
    false,
    true,
    null,
    array['kids','safety','family'],
    27
  ),
  (
    'visitors-and-the-doorbell-a-management-plan',
    'Visitors and the Doorbell: A Management Plan',
    'The doorbell predicts excitement, so dogs explode. Change what the sound predicts and manage arrivals while the new habit forms.',
    $$[
      {"type":"paragraph","text":"For most dogs the doorbell is the most reliable signal in the house: it always means someone is about to appear. Barking and rushing the door are rehearsed every single delivery. You will need two things, a management plan for real arrivals and a training plan for the sound."},
      {"type":"heading","level":2,"text":"Manage real arrivals"},
      {"type":"checklist","items":["Put a gate across the hallway, or use a leash or a closed door, before you answer","Keep a jar of treats near the door","Scatter a handful of treats on the floor away from the door as the bell goes","Ask delivery drivers to leave parcels without ringing, and put a note on the door","Text guests to message on arrival instead of knocking","Let your dog greet only once they can keep four paws on the floor"]},
      {"type":"heading","level":2,"text":"Change what the bell means"},
      {"type":"bullets","items":["Record your doorbell or knock on your phone","Play it at very low volume, then immediately drop several treats on your dog's mat","Repeat until the sound makes your dog look at the mat","Raise the volume gradually across sessions","Move to the real bell with a helper outside, still paying on the mat","Add opening the door, then a familiar person stepping in, one piece at a time"]},
      {"type":"tip","text":"A few barks at a surprise sound are normal dog behavior. Aim for a dog who barks once or twice and then runs to their mat, not for silence."},
      {"type":"warning","text":"If your dog is frightened of visitors rather than excited, with backing away, hard staring, growling, or barking that continues after the guest sits down, do not push greetings. Let your dog stay behind a gate with something to chew and seek professional guidance."},
      {"type":"paragraph","text":"Management is not cheating. Every arrival your dog spends behind a gate eating scattered treats is an arrival where the old habit did not get stronger. Pawly's Door manners and Barking courses take the training side further, step by step."}
    ]$$::jsonb,
    'Barking',
    'intermediate',
    5,
    false,
    true,
    null,
    array['doorbell','visitors','management'],
    28
  ),
  (
    'car-travel-safe-setup-and-motion-sickness-basics',
    'Car Travel: Safe Setup and Motion Sickness Basics',
    'A secure travel crate or harness, short practice trips, and a conversation with your vet solve most car problems.',
    $$[
      {"type":"paragraph","text":"Dogs who dislike the car are usually either feeling sick, feeling unsafe, or have learned that the car only goes to unpleasant places. It helps to work out which one you are dealing with, because the fixes are different."},
      {"type":"heading","level":2,"text":"Safe setup first"},
      {"type":"checklist","items":["Use a secured travel crate or a crash-tested car harness on the back seat or in the cargo area","Never let a dog ride on a lap or in a front seat with an active airbag","Keep heads inside the window. Flying debris injures eyes and ears","Put a non-slip mat or familiar bedding under your dog","Carry water and plan a break every two hours on long trips","Never leave a dog in a parked car. Temperatures become dangerous within minutes, even on mild days"]},
      {"type":"heading","level":2,"text":"Build the habit gradually"},
      {"type":"bullets","items":["If you use a travel crate, make it familiar in the house before it goes in the car","Feed treats in the parked car with the engine off, then get out","Add the engine running, then the end of the driveway, then around the block","Make most early trips end somewhere your dog enjoys","Keep each step short enough that your dog stays relaxed"]},
      {"type":"heading","level":2,"text":"Signs of motion sickness"},
      {"type":"bullets","items":["Drooling, lip licking, or repeated swallowing","Yawning, whining, or restlessness","Going very still and quiet","Vomiting during or shortly after a trip"]},
      {"type":"paragraph","text":"Motion sickness is common in puppies and many grow out of it as the inner ear matures. In the meantime, keep the car cool with fresh air, drive smoothly, let your dog face forward where possible, and avoid travel right after a large meal."},
      {"type":"tip","text":"A dog who has been sick in the car several times may start to feel anxious at the sight of it. Treat the nausea first, then rebuild the good associations."},
      {"type":"warning","text":"Talk to your veterinarian about motion sickness. Effective prescription anti-nausea medication exists. Do not give human travel-sickness tablets or sedatives without veterinary advice."},
      {"type":"paragraph","text":"Once your dog feels physically well and secure in their spot, short happy journeys do the rest. Most dogs come to see the car as the thing that takes them somewhere good."}
    ]$$::jsonb,
    'Crate Training',
    'beginner',
    6,
    false,
    true,
    null,
    array['car travel','motion sickness','travel crate'],
    29
  ),
  (
    'fireworks-and-thunderstorms-how-to-prepare',
    'Fireworks and Thunderstorms: How to Prepare',
    'Noise fear is easier to prevent and manage than to fix on the night. Plan the den, the routine, and the vet conversation in advance.',
    $$[
      {"type":"paragraph","text":"Fear of loud, unpredictable noise is one of the most common problems in pet dogs, and it tends to get worse each year without help. You cannot explain fireworks to a dog, but you can change how exposed they are and how supported they feel."},
      {"type":"heading","level":2,"text":"Weeks before"},
      {"type":"checklist","items":["Talk to your veterinarian if your dog has panicked before. Medication for noise fear works best when planned ahead","Check that your dog's microchip details and ID tag are current","Build a den in an interior room or a covered crate with the door open, and feed treats there daily","Start playing recorded firework or storm sounds at a volume so low your dog barely notices, paired with meals or play","Raise the volume only while your dog stays relaxed, and stop the sound work once the real season starts"]},
      {"type":"heading","level":2,"text":"On the day"},
      {"type":"bullets","items":["Give a good walk and a toilet trip well before dusk","Feed dinner early. Frightened dogs often will not eat","Close windows and curtains, and turn on lights to mask flashes","Play steady background sound such as a fan, white noise, or music with a strong bass line","Offer a long-lasting chew or lick mat in the den","Keep doors, gates, and cat flaps secured, and take garden trips on leash"]},
      {"type":"heading","level":2,"text":"During the noise"},
      {"type":"paragraph","text":"Stay home if you can, act normally, and let your dog choose where to be. If they come to you for comfort, give it. Fear is an emotion, not a behavior, and you cannot reinforce it with kindness. If they want to hide, let them hide."},
      {"type":"tip","text":"Some dogs cope better with a game. If your dog will play or take treats, pair each bang with a tossed treat or a tug. If they will not eat, do not push it."},
      {"type":"warning","text":"Never take a noise-sensitive dog to a display, and never tell them off for shaking, barking, or toileting indoors during a fright. Dogs who injure themselves trying to escape, or who take hours to recover, need veterinary help."},
      {"type":"paragraph","text":"After the season, go back to the sound work at low volume and keep the den as a year-round safe place. Each well-managed event makes the next one a little easier."}
    ]$$::jsonb,
    'Settling',
    'intermediate',
    6,
    false,
    true,
    null,
    array['fireworks','thunderstorms','noise fear'],
    30
  ),
  (
    'adopting-a-rescue-dog-the-3-3-3-guideline',
    'Adopting a Rescue Dog: The 3-3-3 Guideline',
    'Three days, three weeks, three months. It is a rough rule of thumb, not science, but it sets helpful expectations.',
    $$[
      {"type":"paragraph","text":"Rescue organizations often share the 3-3-3 guideline to describe how a newly adopted dog settles. It is not based on research and no dog follows it exactly. Its value is in reminding you that the dog you meet in week one is not yet the dog you will live with."},
      {"type":"heading","level":2,"text":"The rough stages"},
      {"type":"bullets","items":["First 3 days: overwhelmed. Your dog may not eat much, may hide or sleep a lot, or may seem unusually quiet or unusually wired","First 3 weeks: settling. Routines start to make sense, personality appears, and some unwanted behaviors may surface as your dog relaxes","First 3 months: at home. Trust builds, your dog knows the household pattern, and real training progress becomes steady"]},
      {"type":"paragraph","text":"Some dogs move through this in days. Fearful dogs, or those with a difficult history, can take six months or longer. Let your dog's behavior set the pace, not the calendar."},
      {"type":"heading","level":2,"text":"The first days"},
      {"type":"checklist","items":["Set up a quiet retreat with a bed, water, and a chew, and let your dog use it undisturbed","Keep the same times for meals, toilet trips, and sleep","Hold off on visitors, dog parks, pet stores, and big outings","Let your dog approach you. Avoid reaching over their head or hugging","Use secure, well-fitted equipment. New dogs are a flight risk, so consider a harness and collar with two points of attachment","Supervise all contact with children and resident pets"]},
      {"type":"heading","level":2,"text":"Starting training"},
      {"type":"bullets","items":["Begin with rewarding anything you like: eye contact, four paws on the floor, lying down","Hand-feed some meals to build trust","Teach a name response and a simple hand target before formal cues","Keep sessions to a minute or two and end on a success"]},
      {"type":"tip","text":"Book a vet check in the first week or two. It establishes a baseline, and it rules out pain or illness as a cause of any behavior you are seeing."},
      {"type":"warning","text":"A honeymoon period is common. Guarding, reactivity, or separation distress can appear weeks in, once the dog feels secure enough to show it. That is not a failure. Get help from a qualified force-free professional early."},
      {"type":"paragraph","text":"Low expectations and a predictable routine are the kindest start you can give. Go slowly for the first month and you will rarely regret it."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    6,
    false,
    true,
    null,
    array['rescue','adoption','settling in'],
    31
  ),
  (
    'muzzle-training-as-a-kindness',
    'Muzzle Training as a Kindness',
    'A muzzle your dog has been taught to enjoy is a safety tool, not a punishment. Every dog benefits from learning to wear one.',
    $$[
      {"type":"paragraph","text":"Muzzles carry a stigma they do not deserve. A dog wearing one is usually a dog with a responsible owner. Any dog may need a muzzle one day: after an injury, at the vet, because of local rules, or to stop them eating dangerous things on walks. Dogs who meet the muzzle for the first time in an emergency find it frightening. Dogs who learned it as a treat game do not."},
      {"type":"heading","level":2,"text":"Choose the right type"},
      {"type":"checklist","items":["A basket muzzle, which lets your dog pant fully, drink, and take treats","Enough length that it does not press on the nose, and enough depth for an open-mouth pant","Straps that sit snug behind the ears, with room for one finger underneath","Avoid tight fabric grooming muzzles for anything longer than a brief procedure. They hold the mouth shut and prevent panting"]},
      {"type":"heading","level":2,"text":"Teach it in small steps"},
      {"type":"bullets","items":["Show the muzzle, then treat. Repeat until the sight of it makes your dog look happy","Hold it like a cup and feed treats through the front so your dog pushes their nose in by choice","Build to a few seconds with the nose inside while you feed steadily","Lift the straps behind the ears for a second, then release and treat","Fasten it, feed several treats, and unfasten. Keep it under five seconds at first","Add duration slowly, then add movement: a few steps, a short game, a short walk"]},
      {"type":"paragraph","text":"Expect this to take days to weeks of one- or two-minute sessions. If your dog paws at the muzzle or backs away, you moved ahead too fast. Go back to the last easy step."},
      {"type":"tip","text":"Cheese spread or a lickable treat squeezed from a tube works well through basket bars. Make the muzzle predict your dog's best food, and only that food."},
      {"type":"warning","text":"A muzzle manages risk. It does not change how your dog feels. Never use one to place a dog in situations they cannot cope with, and never leave a muzzled dog unattended. For aggression, work with a veterinary behaviorist or certified behavior consultant."},
      {"type":"paragraph","text":"A muzzle-trained dog can be examined safely when in pain, can walk in places that would otherwise be off limits, and gives everyone around them a little more room. It is one of the most useful skills you can teach."}
    ]$$::jsonb,
    'Reactivity',
    'intermediate',
    6,
    false,
    true,
    null,
    array['muzzle training','safety','cooperative care'],
    32
  ),
  (
    'when-to-hire-a-professional-and-how-to-choose-one',
    'When to Hire a Professional and How to Choose One',
    'Dog training is unregulated, so credentials and methods matter. Know when an app is not enough and what to ask before you book.',
    $$[
      {"type":"paragraph","text":"Anyone can call themselves a dog trainer or behaviorist. There is no license required in most places. That makes choosing well your responsibility, and it is worth doing carefully because the wrong help can make fear and aggression worse."},
      {"type":"heading","level":2,"text":"When to get help"},
      {"type":"checklist","items":["Any bite, or growling and snapping at people or other pets","Guarding food, toys, places, or people","Panic when left alone: destruction at exits, howling, drooling, self-injury","Fear that is not improving, or is spreading to new things","Reactivity that makes walks unmanageable","Any sudden change in behavior. See your veterinarian first to rule out pain or illness","You have followed a plan consistently for a few weeks and nothing has changed"]},
      {"type":"heading","level":2,"text":"Credentials worth looking for"},
      {"type":"bullets","items":["CCPDT: CPDT-KA for trainers, CBCC-KA for behavior consultants","IAABC: certified and accredited dog behavior consultants and trainers","KPA CTP: Karen Pryor Academy Certified Training Partner","Veterinary behaviorists: veterinarians with specialist board certification in behavior, such as DACVB in North America. They can diagnose and prescribe","In other countries, look for the equivalent independent bodies, such as ABTC-registered practitioners in the UK"]},
      {"type":"paragraph","text":"A certificate is a starting point, not a guarantee. Ask about methods as well."},
      {"type":"heading","level":2,"text":"Questions to ask"},
      {"type":"bullets","items":["What happens when my dog gets it right?","What happens when my dog gets it wrong?","What equipment do you use, and is there anything you will not use?","Can I watch a session or a class first?","How do you work with my veterinarian?"]},
      {"type":"warning","text":"Walk away from guaranteed results, talk of dominance, alpha, or pack leadership, and any use of prong, choke, or shock collars, leash corrections, or pinning. Leading veterinary behavior organizations advise against aversive methods because of the risk of increased fear and aggression."},
      {"type":"tip","text":"For serious aggression or anxiety, start with your veterinarian and ask about referral to a veterinary behaviorist. Many now offer remote consultations alongside your regular vet."},
      {"type":"paragraph","text":"Pawly is built for everyday training and common problems. It is not a substitute for in-person help when safety is involved. A good professional will be glad to explain exactly what they do and why."}
    ]$$::jsonb,
    'Handler Skills',
    'beginner',
    6,
    false,
    true,
    null,
    array['professional help','trainer credentials','behaviorist'],
    33
  ),
  (
    'training-your-senior-dog-adjustments-that-help',
    'Training Your Senior Dog: Adjustments That Help',
    'Old dogs learn new things very well. They need shorter sessions, kinder surfaces, and an owner who checks for pain first.',
    $$[
      {"type":"paragraph","text":"Training is one of the best things you can do for an older dog. It keeps the mind active, keeps the two of you connected, and gives you a way to notice small changes early. What needs to change is the physical side of how you ask."},
      {"type":"heading","level":2,"text":"Check the body first"},
      {"type":"paragraph","text":"A senior dog who stops sitting on cue, hesitates on stairs, or becomes grumpy about handling is more likely to be sore than stubborn. Arthritis, dental pain, and failing sight or hearing are all common and often treatable. Ask your veterinarian for a senior check before you treat any new behavior as a training issue."},
      {"type":"heading","level":2,"text":"Adjust the setup"},
      {"type":"checklist","items":["Train on rugs, mats, or grass, never on slippery floors","Keep sessions to two or three minutes with breaks","Swap repeated sits and downs for standing behaviors, nose targets, and chin rests","Use soft, smelly treats that are easy to chew and easy to find","Pair every verbal cue with a clear hand signal in case hearing fades","For dogs with poor sight, use touch cues, scent, and consistent furniture layout","Warm up with a short, gentle walk before asking for movement"]},
      {"type":"heading","level":2,"text":"Good activities for older dogs"},
      {"type":"bullets","items":["Scent games and scatter feeding","Easy food puzzles and lick mats","Slow sniffing walks on soft ground","Gentle tricks such as hand target, chin rest, and paw lift if comfortable","Cooperative care practice, which makes the extra vet visits of old age easier"]},
      {"type":"tip","text":"Let your dog choose the position. If a down is uncomfortable, a relaxed stand on a mat is a perfectly good settle."},
      {"type":"warning","text":"Disorientation, staring at walls, pacing or waking at night, new house soiling, or no longer recognizing familiar people can be signs of canine cognitive dysfunction or other illness. See your veterinarian. Several of these conditions can be managed."},
      {"type":"paragraph","text":"Seniors often have better focus than they did at two. Meet them where their body is, keep it light, and training becomes a comfortable daily ritual you will both value."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    5,
    false,
    true,
    null,
    array['senior dogs','aging','adjustments'],
    34
  )
on conflict (slug) do update
set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  category = excluded.category,
  difficulty = excluded.difficulty,
  read_time_minutes = excluded.read_time_minutes,
  is_featured = excluded.is_featured,
  is_published = excluded.is_published,
  cover_image_url = excluded.cover_image_url,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  updated_at = now();
