insert into public.articles (
  slug,
  title,
  excerpt,
  content,
  category,
  difficulty,
  read_time_minutes,
  is_featured,
  is_published,
  cover_image_url,
  tags,
  sort_order
)
values
  (
    'how-to-start-training-a-dog-without-overcomplicating-it',
    'How to Start Training a Dog Without Overcomplicating It',
    'Most dogs do better when training is simple, short, and repeatable. Start with clarity, not a perfect plan.',
    $$[
      {"type":"paragraph","text":"A good training plan does not need ten cues, a color-coded chart, or a bag full of gadgets. Most dogs improve fastest when the handler gets consistent about a few basics."},
      {"type":"heading","level":2,"text":"Start with one clear job"},
      {"type":"paragraph","text":"Pick one practical behavior to work on for the week. That might be settling on a mat, coming when called in the yard, or walking without dragging you down the block. When the goal is clear, your timing gets cleaner."},
      {"type":"checklist","items":["Choose one skill your dog can practice daily","Train for 3 to 8 minutes at a time","Use the same cue and the same reward pattern","End before your dog checks out"]},
      {"type":"tip","text":"If you feel tempted to add more difficulty, first ask whether your dog is already getting 8 out of 10 repetitions right."},
      {"type":"heading","level":2,"text":"Build a repeatable routine"},
      {"type":"bullets","items":["Set up before you cue anything","Mark the exact moment your dog gets it right","Pay quickly so the dog understands what earned the reward","Take short pauses instead of drilling repetition after repetition"]},
      {"type":"warning","text":"If your dog is getting confused, do not repeat the cue louder or faster. Make the task easier and help them succeed."},
      {"type":"paragraph","text":"Simple training looks almost boring from the outside. That is usually a good sign. Clear reps, clear rewards, and calm endings build the kind of progress that holds up in real life."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    5,
    true,
    true,
    null,
    array['getting started','training basics','routine'],
    1
  ),
  (
    'why-your-dog-is-not-listening-outside',
    'Why Your Dog Is Not Listening Outside',
    'Outside is harder because the environment is louder, richer, and more rewarding than your living room. That is normal, not stubbornness.',
    $$[
      {"type":"paragraph","text":"Many dogs look fluent indoors and then seem to forget everything outside. Usually the cue is not broken. The environment is simply much harder."},
      {"type":"heading","level":2,"text":"What changes outside"},
      {"type":"bullets","items":["Movement is everywhere","Scents pull attention away from you","Distance from you often increases","Arousal rises before you even start training"]},
      {"type":"paragraph","text":"When those factors stack up, your dog may not be capable of doing the same version of the skill they can do at home. That does not mean they are ignoring you on purpose."},
      {"type":"heading","level":2,"text":"How to make outside doable"},
      {"type":"checklist","items":["Start in the easiest outdoor spot you have","Cut the session length in half","Use better rewards than you use indoors","Ask for one or two easy wins before trying the main skill"]},
      {"type":"tip","text":"If your dog cannot respond, increase distance from the distraction before asking again."},
      {"type":"warning","text":"Repeating cues in a busy environment teaches your dog that the first few repetitions do not matter."},
      {"type":"paragraph","text":"Think of outdoor training as a new level, not a test. Train it like a new level and your dog will usually come back online much faster."}
    ]$$::jsonb,
    'Handler Skills',
    'beginner',
    4,
    false,
    true,
    null,
    array['outdoors','distractions','focus'],
    2
  ),
  (
    'loose-leash-walking-the-first-things-to-fix',
    'Loose Leash Walking: The First Things to Fix',
    'Before you ask for a perfect heel, fix the setup, pace, and reward timing that make pulling more likely.',
    $$[
      {"type":"paragraph","text":"Loose leash walking usually falls apart for simple reasons. The dog is moving too fast, the handler is too late, or the environment is more exciting than the current skill level can handle."},
      {"type":"heading","level":2,"text":"Fix your starting picture"},
      {"type":"checklist","items":["Begin before your dog hits full excitement","Stand still until the leash softens","Reward near your leg, not out in front","Keep the first thirty seconds easy"]},
      {"type":"heading","level":2,"text":"Watch what your rewards are teaching"},
      {"type":"paragraph","text":"If treats always appear after the dog surges ahead, you may be paying the forward push instead of the loose leash moment. Feed where you want the dog to be."},
      {"type":"bullets","items":["Shorten the route","Slow your pace","Mark any glance back or check-in","Turn earlier instead of fighting tension for ten steps"]},
      {"type":"tip","text":"A loose leash is not just about position. It is also about rhythm. Reward the dog for staying connected to your pace."},
      {"type":"warning","text":"Do not keep walking through steady pulling. Movement itself can be the reward that maintains the behavior."},
      {"type":"paragraph","text":"Early leash work should feel controlled and a little repetitive. That foundation matters more than logging a long walk with bad mechanics."}
    ]$$::jsonb,
    'Leash Walking',
    'beginner',
    6,
    true,
    true,
    null,
    array['leash walking','pulling','mechanics'],
    3
  ),
  (
    'how-to-teach-recall-without-repeating-come',
    'How to Teach Recall Without Repeating “Come”',
    'Reliable recall comes from setup and follow-through, not from saying the cue over and over.',
    $$[
      {"type":"paragraph","text":"If you say come three times before your dog moves, the problem is usually not that your dog needs more volume. The dog has learned that the first cue is optional or the environment is still too hard."},
      {"type":"heading","level":2,"text":"Make the cue valuable again"},
      {"type":"bullets","items":["Use the cue once","Move backward or create motion after the cue","Reward generously when your dog commits to you","Release the dog again sometimes so recall does not always end the fun"]},
      {"type":"heading","level":2,"text":"Train the easy versions first"},
      {"type":"checklist","items":["Inside across one room","In the yard on a long line","In a quiet outdoor spot with low distraction","Around mild distractions with distance"]},
      {"type":"tip","text":"Use a long line when you are not certain your dog can succeed. That protects the cue while you build repetition."},
      {"type":"warning","text":"Avoid using recall only for unpleasant outcomes like baths, nail trims, or the immediate end of play."},
      {"type":"paragraph","text":"Recall gets stronger when the dog has a long history of hearing the cue once, turning fast, and finding something good when they arrive."}
    ]$$::jsonb,
    'Recall',
    'intermediate',
    5,
    false,
    true,
    null,
    array['recall','come cue','long line'],
    4
  ),
  (
    'what-to-do-when-your-dog-jumps-on-guests',
    'What to Do When Your Dog Jumps on Guests',
    'Jumping is often social overexcitement plus a rehearsal problem. Change the setup before you expect better manners.',
    $$[
      {"type":"paragraph","text":"Most dogs jump on guests because the arrival is chaotic and the behavior has worked before. Attention, touch, and forward movement all keep the pattern alive."},
      {"type":"heading","level":2,"text":"Solve it before the door opens"},
      {"type":"checklist","items":["Put your dog on leash before the greeting","Have treats ready in reach","Tell guests exactly what to do","Pick a simple alternative behavior such as four paws down or go to mat"]},
      {"type":"heading","level":2,"text":"During the greeting"},
      {"type":"bullets","items":["If paws leave the floor, guest steps back","The moment paws return, mark and reward","Keep greetings brief at first","Reset early instead of waiting for the dog to spiral"]},
      {"type":"tip","text":"If your dog gets too excited to think, rehearse with a familiar person before trying it with real visitors."},
      {"type":"warning","text":"Pushing the dog off with your hands can feel like interaction and may add more excitement."},
      {"type":"paragraph","text":"The goal is not to suppress enthusiasm. It is to teach your dog that calm behavior is what keeps greetings going."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    5,
    false,
    true,
    null,
    array['jumping','guests','greetings'],
    5
  ),
  (
    'crate-training-without-creating-more-stress',
    'Crate Training Without Creating More Stress',
    'A crate should feel predictable and safe. If the dog is escalating, the plan is probably moving faster than the dog can handle.',
    $$[
      {"type":"paragraph","text":"Crate training works best when it is introduced as a calm routine, not a showdown. The goal is not just physical containment. The goal is relaxation."},
      {"type":"heading","level":2,"text":"What to build first"},
      {"type":"checklist","items":["Dog willingly enters for food","Dog can stay in the crate briefly with the door open","Dog can handle the door closing for a second or two","Dog can relax before duration is increased"]},
      {"type":"bullets","items":["Feed some meals in the crate","Use a soft predictable cue for entering","Keep early exits calm and boring","Increase one variable at a time"]},
      {"type":"tip","text":"If your dog settles more easily with a chew or scatter of treats, use that support while the crate routine is still new."},
      {"type":"warning","text":"Extended distress is information, not something to push through. Back up to a version the dog can tolerate and rebuild from there."},
      {"type":"paragraph","text":"Crate training tends to improve when sessions stay short, successful, and routine. Small wins are what make the crate usable later in real life."}
    ]$$::jsonb,
    'Crate Training',
    'beginner',
    6,
    false,
    true,
    null,
    array['crate training','home setup','stress reduction'],
    6
  ),
  (
    'how-to-help-an-overexcited-dog-settle',
    'How to Help an Overexcited Dog Settle',
    'Settling is easier to teach when you lower overall arousal first and then reward the specific quiet behaviors you want to see more often.',
    $$[
      {"type":"paragraph","text":"Dogs do not usually settle because we ask once. They settle because the environment, the routine, and the reinforcement history all support quieter behavior."},
      {"type":"heading","level":2,"text":"Start by reducing pressure"},
      {"type":"bullets","items":["Use a quieter room","Lower your own energy","Shorten the session","Put food delivery on the floor or mat instead of in the air"]},
      {"type":"heading","level":2,"text":"Reward the small signs"},
      {"type":"checklist","items":["A pause instead of pacing","A hip shift or sit","A lowered head","Any return to the mat or bed"]},
      {"type":"tip","text":"If your dog struggles to settle after exciting activity, add a few minutes of decompression before you train relaxation."},
      {"type":"warning","text":"Do not wait for perfect stillness before rewarding. If you miss the early quiet moments, the dog has less reason to offer them again."},
      {"type":"paragraph","text":"A settled dog is usually built through repetition of small calm moments, not one big breakthrough. Treat the first half of the process as observation and reinforcement."}
    ]$$::jsonb,
    'Settling',
    'beginner',
    5,
    false,
    true,
    null,
    array['settle','calmness','mat work'],
    7
  ),
  (
    'puppy-biting-what-is-normal-and-what-helps',
    'Puppy Biting: What Is Normal and What Helps',
    'Puppy biting is common, but it still needs management. Clear patterns and better outlets usually help faster than reacting emotionally.',
    $$[
      {"type":"paragraph","text":"Puppies explore with their mouths. That part is normal. What matters is reducing rehearsal, giving better targets, and noticing when biting spikes because the puppy is tired, overexcited, or frustrated."},
      {"type":"heading","level":2,"text":"What helps most"},
      {"type":"checklist","items":["Keep toys within reach","Interrupt early before the puppy escalates","Use short rest breaks","Notice predictable bitey times during the day"]},
      {"type":"bullets","items":["Redirect to a toy","Freeze briefly if movement is fueling the game","End interaction calmly when teeth keep returning to skin","Lower intensity instead of wrestling through it"]},
      {"type":"heading","level":2,"text":"What to watch"},
      {"type":"warning","text":"Very rough handling, punishment, or frantic squealing can make some puppies more aroused and more mouthy."},
      {"type":"tip","text":"A lot of puppy biting happens when the puppy is due for sleep, food, or a calmer activity."},
      {"type":"paragraph","text":"You are not trying to win an argument with a baby dog. You are teaching better habits and protecting everyone while those habits are still being learned."}
    ]$$::jsonb,
    'Puppy Training',
    'beginner',
    5,
    false,
    true,
    null,
    array['puppy','biting','management'],
    8
  ),
  (
    'the-real-reason-your-sessions-fall-apart',
    'The Real Reason Your Sessions Fall Apart',
    'Most messy sessions fail from stacking too much difficulty, not from a lack of effort.',
    $$[
      {"type":"paragraph","text":"When a session falls apart, it is tempting to say the dog was stubborn or distracted. More often, the session got too hard too quickly and the dog lost the ability to stay successful."},
      {"type":"heading","level":2,"text":"Common ways difficulty sneaks up"},
      {"type":"bullets","items":["Too many reps without a break","New environment plus harder criteria","Session starts after arousal is already high","Rewards are too slow or too low value"]},
      {"type":"heading","level":2,"text":"What to change next time"},
      {"type":"checklist","items":["Set one main goal","Lower either duration, distance, or distraction","Plan your first reward before you begin","Stop after a few strong reps instead of chasing one more"]},
      {"type":"tip","text":"If you keep thinking your dog should have gotten it, that is often a sign the setup was optimistic."},
      {"type":"warning","text":"Pushing through a session that is clearly unraveling often teaches the dog to rehearse the very behavior you were trying to fix."},
      {"type":"paragraph","text":"Good handlers are not the ones who never have hard sessions. They are the ones who notice the drift early and simplify before everything crashes."}
    ]$$::jsonb,
    'Handler Skills',
    'intermediate',
    4,
    true,
    true,
    null,
    array['session planning','criteria','timing'],
    9
  ),
  (
    'how-to-use-rewards-without-bribing-your-dog',
    'How to Use Rewards Without Bribing Your Dog',
    'Rewards do not become bribes just because your dog can see them. The real issue is whether the dog is following the cue or the visible food lure.',
    $$[
      {"type":"paragraph","text":"People often worry that food rewards create dependency. In practice, rewards are how dogs learn what worked. The problem comes when the reward is shown first every single time and becomes the only reason the dog moves."},
      {"type":"heading","level":2,"text":"What a reward does"},
      {"type":"bullets","items":["Marks success","Builds motivation to try again","Increases clarity","Makes good behavior worth repeating"]},
      {"type":"heading","level":2,"text":"How to avoid accidental bribing"},
      {"type":"checklist","items":["Give the cue before reaching for food","Hide rewards off your body or in a pouch","Use the same marker word each time","Fade visible lures once the dog understands the motion"]},
      {"type":"tip","text":"If your dog only responds when the treat is already in your fingers, go back and separate the cue from the visible food presentation."},
      {"type":"warning","text":"Removing rewards too early often makes behavior less reliable, especially in new environments."},
      {"type":"paragraph","text":"A strong reward system does not make training weaker. It usually makes it clearer, faster, and easier to generalize."}
    ]$$::jsonb,
    'Basics',
    'beginner',
    5,
    false,
    true,
    null,
    array['rewards','food training','motivation'],
    10
  ),
  (
    'building-focus-around-distractions',
    'Building Focus Around Distractions',
    'Focus around distractions is built by controlling distance and difficulty, not by demanding eye contact in the middle of overwhelm.',
    $$[
      {"type":"paragraph","text":"Focus is not all-or-nothing. A dog can be aware of the environment and still stay responsive if the setup is fair."},
      {"type":"heading","level":2,"text":"Train under threshold"},
      {"type":"paragraph","text":"Your dog should be able to notice the distraction without tipping into frantic pulling, barking, or complete disconnection. That usually means starting farther away than people expect."},
      {"type":"checklist","items":["Find the distance where your dog can still eat","Reward check-ins quickly","Leave before attention fully collapses","Repeat in short bursts instead of one long exposure"]},
      {"type":"heading","level":2,"text":"Use focus functionally"},
      {"type":"bullets","items":["Reward a glance back at you","Reward moving with you","Reward a calm pause","Reward choosing not to escalate"]},
      {"type":"tip","text":"Focus does not always need to mean staring at your face. Movement with you and quick check-ins count."},
      {"type":"warning","text":"If your dog is already vocalizing or lunging, asking for more precision usually backfires. First regain enough distance for the dog to think."},
      {"type":"paragraph","text":"Steady progress comes from lots of manageable exposures. The dog learns that noticing the world and reconnecting with you can happen in the same moment."}
    ]$$::jsonb,
    'Reactivity',
    'intermediate',
    6,
    false,
    true,
    null,
    array['reactivity','focus','threshold'],
    11
  ),
  (
    'a-better-way-to-end-a-training-session',
    'A Better Way to End a Training Session',
    'The last minute of a session affects how eager your dog feels next time. End on something clear, easy, and calm.',
    $$[
      {"type":"paragraph","text":"A lot of handlers end sessions by squeezing in one more hard rep. That can leave both dog and human frustrated. A better ending helps the next session start stronger."},
      {"type":"heading","level":2,"text":"What a good ending looks like"},
      {"type":"checklist","items":["One easy success your dog understands","A quick payoff","A calm release","No frantic repetition right before you stop"]},
      {"type":"bullets","items":["Return to a simpler version of the skill","Use a predictable finish phrase","Let your dog decompress after the work","Make notes after the session, not during your last rep"]},
      {"type":"tip","text":"If the session was hard, your ending should usually be easier than the middle."},
      {"type":"warning","text":"Stopping only after mistakes can accidentally make errors the final memory of the session."},
      {"type":"paragraph","text":"Ending well is not about pretending the session was perfect. It is about giving your dog one clear win before you both move on."}
    ]$$::jsonb,
    'Handler Skills',
    'beginner',
    4,
    false,
    true,
    null,
    array['session endings','motivation','handler timing'],
    12
  ),
  (
    'why-your-dog-barks-and-what-to-change-first',
    'Why Your Dog Barks and What to Change First',
    'Barking is not one problem. The first fix is figuring out what keeps that barking pattern alive.',
    $$[
      {"type":"paragraph","text":"Dogs bark for different reasons: alarm, frustration, excitement, distance-increasing, or habit. Your first job is not to silence the sound. It is to understand the pattern around it."},
      {"type":"heading","level":2,"text":"Look for the trigger pattern"},
      {"type":"checklist","items":["What happens right before barking starts","How close the trigger is","Whether barking works to make something go away","How quickly your dog recovers afterward"]},
      {"type":"bullets","items":["Reduce exposure to the hardest triggers for now","Increase distance where possible","Reward moments of quiet before barking starts","Give your dog another action they can do in that same moment"]},
      {"type":"tip","text":"If barking happens at windows or fences, management matters. Rehearsal keeps the habit strong."},
      {"type":"warning","text":"Correcting barking without understanding the emotion behind it can add more stress and more intensity."},
      {"type":"paragraph","text":"When you change the setup and reward calmer choices early, barking often becomes much easier to work on."}
    ]$$::jsonb,
    'Barking',
    'intermediate',
    5,
    false,
    true,
    null,
    array['barking','triggers','management'],
    13
  ),
  (
    'handler-timing-the-skill-most-owners-underestimate',
    'Handler Timing: The Skill Most Owners Underestimate',
    'Dogs learn from the moment you reinforce, not the behavior you meant to reinforce. Cleaner timing changes everything.',
    $$[
      {"type":"paragraph","text":"A dog can know roughly what you want and still struggle because the timing from the handler is muddy. Fast, clear feedback makes training easier on both sides of the leash."},
      {"type":"heading","level":2,"text":"What better timing looks like"},
      {"type":"bullets","items":["Mark the exact choice you want repeated","Deliver food quickly after the marker","Reset calmly instead of talking through mistakes","Keep your body movement predictable"]},
      {"type":"heading","level":2,"text":"How to improve without overthinking"},
      {"type":"checklist","items":["Use simpler setups","Train fewer reps at a time","Video one short session and watch your reward timing","Pause between repetitions so you can set up the next one well"]},
      {"type":"tip","text":"If your dog seems inconsistent, look at your own timing before assuming the dog does not understand."},
      {"type":"warning","text":"Constant chatter often delays the marker and makes the picture less clear for the dog."},
      {"type":"paragraph","text":"Cleaner timing is one of the fastest upgrades a handler can make. It reduces confusion without changing the whole training plan."}
    ]$$::jsonb,
    'Handler Skills',
    'advanced',
    5,
    false,
    true,
    null,
    array['timing','markers','handler mechanics'],
    14
  )
on conflict (slug) do update
set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  category = excluded.category,
  difficulty = excluded.difficulty,
  read_time_minutes = excluded.read_time_minutes,
  is_featured = excluded.is_featured,
  is_published = excluded.is_published,
  cover_image_url = excluded.cover_image_url,
  tags = excluded.tags,
  sort_order = excluded.sort_order,
  updated_at = now();
